# Generated by Django 3.2.3 on 2022-08-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogo',
            old_name='create',
            new_name='created',
        ),
        migrations.AddField(
            model_name='catalogo',
            name='imagen',
            field=models.ImageField(default='null', upload_to=''),
            preserve_default=False,
        ),
    ]
