# Generated by Django 3.2.3 on 2022-08-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_auto_20220803_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='imagen',
            field=models.ImageField(upload_to='catalogos/'),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='revista',
            field=models.FileField(upload_to='catalogos/'),
        ),
    ]
