# Generated by Django 3.2.3 on 2022-08-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=30, null=True),
        ),
    ]
