# Generated by Django 3.2.3 on 2022-08-06 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineapedido',
            old_name='pedido',
            new_name='pedido_id',
        ),
        migrations.RenameField(
            model_name='lineapedido',
            old_name='producto',
            new_name='producto_id',
        ),
    ]
