# Generated by Django 3.2.3 on 2022-08-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_auto_20220806_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineapedido',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
